### ISSUE TITLE
Control width of a table

### ISSUE THREAD

**Issue by rosen-vladimirov** [mikaelbr/marked-terminal#11]
Hi,
Is it possible to control the width of the table. I couldn't find an option to control the width of the created cli-table. When the text in a table column is very long, small terminals (like cmd) render them in a very strange manner. I know cli-table has option to control the width (colWidths), but is it possible to set it through marked-terminal? 
Thanks for the great work.

**Comment by mikaelbr** [comment]
Hi! Good thinking. Fixed in 42804713dd234bbc17e6a522ae21fa4f2fb3120e.
Thanks for your issue and feedback!

**Comment by rosen-vladimirov** [comment]
@mikaelbr 
Thank you very much. It works now. Have you planned to release a new version, which includes this feature?

**Comment by mikaelbr** [comment]
Hi! Yeah, I though to give it a few days to let it settle and hopefully you test it out. There aren't any issues or outstanding API additions/changes so I think I'll just do this release tomorrow unless anything changes. Sounds good?

**Comment by rosen-vladimirov** [comment]
Hi @mikaelbr , 
Thanks for the quick reply. Yes, it sounds great. I'll continue testing table options and I'll inform you in case I find something and I'll open separate issues for them :)

Thank you very much.

**Comment by mikaelbr** [comment]
```shell
➜  marked-terminal git:(master) npm publish
+ marked-terminal@1.3.0
```
https://github.com/mikaelbr/marked-terminal/releases/tag/v1.3.0
