### ISSUE TITLE
Reflowed text respecting line breaks

### ISSUE THREAD

**Issue by rocky** [mikaelbr/marked-terminal#16]
With [12ecd51139] and the new reflow text, there is now another feature I'd like to add. 

http://daringfireball.net/projects/markdown/syntax#p.text says

> When you do want to insert a &lt;br /&gt; break tag using Markdown, you end a line with two or more spaces, then type return.

My thought here would be complicate *reflowText()* more and do a split on `[ ]{2,}\n ` and then process each group separately. 

Should I make a pass at doing that? 

Also, I probably should expand the regexp in *textLength()* to include more escape sequences. The Ruby package term-aniscolor uses: `/\e\[(?:[34][0-7]|[0-9])?m/`

**Comment by mikaelbr** [comment]
I added you as a collaborator for this. 

I don't know if doing this as a part of `reflowText` is the best, though? Is it really a reflow thing? Wouldn't it be a bit unexpected to not work in "normal mode"? There is a difference between the `<br />` behaviour in Github Flavoured Markdown and not gfm, that you should check out.

**Comment by rocky** [comment]
I'm not sure either. I started coding this only to find that by the time the text gets to *reflowText()*, the trailing blanks have already been stripped out!  I'd be cool with that if it put in some indication that a break should occur at the \n. 

The trailing blanks are getting removed by  *marked*: https://github.com/chjj/marked/blob/master/lib/marked.js#L683-L684 probably via regexp 
`/^[\\s\\S]+?(?=[\\\\<!\\[_*`~]|https?://| {2,}\\n|$)/` which does seem to include GFM  regexps . See https://github.com/chjj/marked/blob/master/lib/marked.js#L497-L514

So does a GFM &lt;br /&gt; work? No, and that does get passed to *reflowText*.  That sucks because *reflowText()* *clearly*  isn't the right place to handle this.

**Comment by rocky** [comment]
Ok. I see what's going on &ndash partially. I tried turning options gfm off and break on and still no reflow.

As is, marked *does* handle the two-or-more space at the end of the line. It turns that into \n. Subsequently, when reflow gets a crack at this, it ignores that since that's what it's supposed to do.

Here is a proposed solution. When the reflow opt is on, instead of break returning "\n", it could return something else like "\r\n" or "\r" "\0", or something else; *reflowText()* can then use that to split on. Other elements will also have to change the "hard-newline" character to \n. 

Using "\r" or "\r\n" is safe in that I believe these are stripped out before hand by https://github.com/chjj/marked/blob/master/lib/marked.js#L138

What do you suggest?

**Comment by mikaelbr** [comment]
Due to how marked works, marked-terminal is full of these sort of "hacks" (temporary translating one string to another to later override it). In a perfect world we wouldn't have to do this, but it seems to be the only solution. So, I think replacing them when reflow is active is a acceptable solution.

**Comment by rocky** [comment]
Commit in. Didn't see the preference for \r or I would have used that. I used \r\n. I see that <br /> inserts a newline, but  it does it keeping the non-space text in there. I'm not sure how that works, but that will have to wait for another time.

Please review the code and make changes as you see fit.

**Comment by rocky** [comment]
And with [2a328046778f41dcccfd09810f008040e89acc46] I think I have gfm line breaks in as well.

**Comment by rocky** [comment]
@mikaelbr  ping.

**Comment by mikaelbr** [comment]
Hi! Sorry for the late response. I've been very busy with a conference. I checked it out now and fixed some bugs and style issues, but it seems to be working good!

**Comment by rocky** [comment]
Thanks!  Could I ask you to put out another release then? 

With the release I'll go over the trepanjs help docs to make use of the hard return and then I can put out another release, bumping the minimum marked-terminal release needed. 

Again, thanks.

**Comment by mikaelbr** [comment]
Could you try out the trepanjs docs first as a test for marked-terminal? You can try out the current master by doing `npm install mikaelbr/marked-terminal` (this would download from github). If your docs works good we know that this is safe and then we can do a minor release.

**Comment by rocky** [comment]
Excellent idea! Working on now.

**Comment by rocky** [comment]
All of the examples in trepanjs check out fine.

**Comment by mikaelbr** [comment]
Cool. I'll do a minor release!

**Comment by rocky** [comment]
Fantastic. And I've also released a new version of trepanjs to take
advantage of this. Much appreciated.
