### ISSUE TITLE
blank lines not working after heading

### ISSUE THREAD

**Issue by vjpr** [mikaelbr/marked-terminal#19]
No matter how many `\n` characters I type I can't get blank lines to show up after the heading.

**Comment by mikaelbr** [comment]
How do you mean? What are you trying. It seems to work fine by me:

```js
var marked = require('marked');
var TerminalRenderer = require('../');

marked.setOptions({ renderer: new TerminalRenderer() });
console.log(marked('# Hello \n\nThis is **markdown** printed in the `terminal`'));
```

<img width="331" alt="screen shot 2015-08-22 at 10 54 42" src="https://cloud.githubusercontent.com/assets/606374/9423247/47072b40-48bc-11e5-99e2-bbefb7e69c81.png">

**Comment by vjpr** [comment]
After `# Hello` its not possible to add a blank line.

**Comment by vjpr** [comment]
```
# Hello

This is markdown printed in....
```

**Comment by mikaelbr** [comment]
Sorry for the late response. This fell through the cracks, somehow.

This is how GFM (Github flavored markdown) behaves. Removing vertical whitespaces when it can. Nothing I can do about it in `marked-terminal` as it works as expected.

You can work around it though. As Markdown is a superset of HTML, you can easily use HTML here. Something like this _should_ work:

console.log(marked('# Hello \n<br />\nThis is **markdown** printed in the `terminal`'));
