### ISSUE TITLE
Port to "remarkable" parser

### ISSUE THREAD

**Issue by Turbo87** [mikaelbr/marked-terminal#22]
It seems that the [marked](https://github.com/chjj/marked/) project is pretty much unmaintained at the moment. Is there any demand for a port of this project to the well maintained [remarkable](https://github.com/jonschlinkert/remarkable) parser? It seems that creating alternative renderers for that parser is supported reasonably well too (see https://github.com/jonschlinkert/pretty-remarkable).

**Comment by Turbo87** [comment]
https://github.com/mikaelbr/cli-usage/issues/2 seems related to this

**Comment by Turbo87** [comment]
apparently not interested...

**Comment by mikaelbr** [comment]
Hi. Sorry for no response. But this wouldn't make much sense for this module as it's a specific plugin/renderer for marked with marked as a peer dependency. So even if this is changed to another implementation than Marked it wouldn't do anything, just break how people are using it.
