### ISSUE TITLE
marked-terminal@1.6.1 requires a peer of marked@^0.3.3 but none was installed.

### ISSUE THREAD

**Issue by rocky** [mikaelbr/marked-terminal#23]
How do I fix? See also https://github.com/rocky/trepanjs/issues/1

$ sudo npm install marked-terminal
[?25l[0GnormalizeTree             ▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GnormalizeTree → install   ▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GnormalizeTree → network   ▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GnormalizeTree → network   ▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GnormalizeTree → 304       ▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GnormalizeTree → headers   ▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → request   ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → headers   ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → network   ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → headers   ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → headers   ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → network   ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → headers   ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▐ ╢███████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → headers   ▌ ╢███████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▄ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▐ ╢████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▐ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▄ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → headers   ▌ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → get       ▄ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → 304       ▌ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0GfetchMetadata → headers   ▌ ╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0Gextract:marked-terminal → ▀ ╢██████████████████████████████████░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0Gextract:marked-terminal → ▌ ╢██████████████████████████████████░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0Gextract:marked-terminal → ▄ ╢██████████████████████████████████░░░░░░░░░░░░░░░╟
[?25h[1A[?25l[0Gextract:node-emoji → gent ▄ ╢███████████████████████████████████████░░░░░░░░░░╟
[?25h[?25h[1A[0G[?25h[0G/src/external-vcs/github
├── UNMET PEER DEPENDENCY marked@^0.3.3
└─┬ marked-terminal@1.6.1 
  ├─┬ cardinal@0.5.0 
  │ ├── ansicolors@0.2.1 
  │ └─┬ redeyed@0.5.0 
  │   └── esprima-fb@12001.1.0-dev-harmony-fb 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├─┬ cli-table@0.3.1 
  │ └── colors@1.0.3 
  ├─┬ lodash.assign@3.2.0 
  │ ├─┬ lodash._baseassign@3.2.0 
  │ │ └── lodash._basecopy@3.0.1 
  │ ├─┬ lodash._createassigner@3.1.1 
  │ │ ├── lodash._bindcallback@3.0.1 
  │ │ ├── lodash._isiterateecall@3.0.9 
  │ │ └── lodash.restparam@3.6.1 
  │ └─┬ lodash.keys@3.1.2 
  │   ├── lodash._getnative@3.9.1 
  │   ├── lodash.isarguments@3.1.0 
  │   └── lodash.isarray@3.0.4 
  └── node-emoji@0.1.0 

[?25h[0Gnpm WARN enoent ENOENT: no such file or directory, open '/src/external-vcs/github/package.json'
[?25h[0Gnpm WARN marked-terminal@1.6.1 requires a peer of marked@^0.3.3 but none was installed.
[?25h[0Gnpm WARN github No description
[?25h[0Gnpm WARN github No repository field.
[?25h[0Gnpm WARN github No README data
[?25h[0Gnpm WARN github No license field.
[?25h[0G[?25h[0G06:14:16  rocky@rocky-sym:/src/external-vcs/github [2,0,b] 0
$

**Comment by mikaelbr** [comment]
Hi! What version of NPM do you use? After NPM 3, they no longer automatically install peer dependencies, but you can install it your self using `npm install -D marked` and it'll hopefully work.

**Comment by rocky** [comment]
Yep. That did it. Thanks!
