### ISSUE TITLE
Could you release 1.6.2?

### ISSUE THREAD

**Issue by sdotson** [mikaelbr/marked-terminal#25]
many repos are up referencing 1.6.2 and it is causing them to break.

**Comment by mikaelbr** [comment]
It should be released:
```
❯ npm show marked-terminal version
1.6.2
```

**Comment by sdotson** [comment]
I just figured out that this is a problem with our corporate npm registry. When I switch to https://registry.npmjs.org/ everything is good. Ugh. Closing.
