### ISSUE TITLE
Please add binary file 

### ISSUE THREAD

**Issue by horosgrisa** [mikaelbr/marked-terminal#28]
Please add binary file (simpre wrapper) who wil be possible to use as markdown reader in terminal.

**Comment by mikaelbr** [comment]
Hi. Thanks for your issue and suggestion. I'm afraid I don't think that is something this package should do. This is simply a plugin, a custom renderer, for the `marked` package, and as such it's not it's business to be a CLI tool.

There are however many tools using this package to achieve what you want. Maybe you could check them out. For instance: https://www.npmjs.com/package/mdy. Or see other packages at NPM: https://www.npmjs.com/browse/depended/marked-terminal

**Comment by Haroenv** [comment]
For other people just wanting a binary, I found that [cli-md](http://yarn.fyi/cli-md) worked better than `mdy`
