### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by Yangfan2016** [mikaelbr/marked-terminal#292]
![image](https://github.com/mikaelbr/marked-terminal/assets/17830872/0f922a11-3cf0-4941-9141-71d5050fbacc)

https://github.com/mikaelbr/marked-terminal/blob/2ddb55e49fc4d5421b203df78b8e07360742bc89/index.js#L263

This  is my code

```js
import { marked } from "marked";
import { markedTerminal } from "marked-terminal";

const c = markedTerminal({});
console.log(1111, c);
marked.use(c);
console.log(222);
const d = marked.parse(
  "# Hello \n This is **markdown** printed in the `terminal`"
);
console.log(d);

```

----

Env info

    "marked": "^13.0.0",
    "marked-terminal": "^7.0.0"

   node:"16.20.1" 
  pnpm:"7.33.7"

**Comment by sinamathew** [comment]
Could you explain your issue better or rephrase...

**Comment by mikaelbr** [comment]
Closing due to no response. If repro is provided we'll reopen.
