### ISSUE TITLE
Marked-terminal doesn't support marked  > v14

### ISSUE THREAD

**Issue by confleux** [mikaelbr/marked-terminal#323]
Marked-terminal doesn't support [marked](https://www.npmjs.com/package/marked)  > v14, which makes using both marked >= v14 and marked-terminal = v.7.0.1 impossible.

**Comment by jackw** [comment]
I've just come up against this too whilst trying to bump marked in a project. A PR was merged to fix this in https://github.com/mikaelbr/marked-terminal/pull/303 but I don't think it's been released yet.

@mikaelbr any chance of releasing a new version of this package so we can update to `marked@14.x.x` please?

**Comment by mikaelbr** [comment]
Should be fixed in `marked-terminal@7.2.0` now
