### ISSUE TITLE
Issues with rendering nested list items

### ISSUE THREAD

**Issue by devinivy** [mikaelbr/marked-terminal#39]
Some funky things are going on with spacing of deeply nested list items, as mentioned in #37 and demonstrated in the tests on https://github.com/mikaelbr/marked-terminal/tree/nested-lists.

@mikaelbr I'm looking into it, and can see it has to do with chalk's ansi interacting with some regex-based checks, i.e. when adding bullets to list items.  Will tinker with it a bit more and either propose a fix or let you know what I've learned.

**Comment by mikaelbr** [comment]
Interesting! Thanks for checking it out. Good work

**Comment by mikaelbr** [comment]
Did you do any progress on this, @devinivy?

**Comment by devinivy** [comment]
I haven't for a little while, but believe it or not, it has been on my mind recently :)

**Comment by mikaelbr** [comment]
Hehe, funny coincidence 😄 Let me know if you figure something out 👍

**Comment by mikaelbr** [comment]
With master and #47 is it better?

**Comment by mikaelbr** [comment]
Closed under the assumption that #47 improved the functionality. Reopen if that is not the case
