### ISSUE TITLE
Support for marked@0.6.0

### ISSUE THREAD

**Issue by mitschmidt** [mikaelbr/marked-terminal#49]
Thanks for this great package.

Unfortunately after updating `marked` to `0.6.0`, npm install complains about the version:
```npm[app] WARN marked-terminal@3.1.1 requires a peer of marked@^0.4.0 || ^0.5.0 but none is installed. You must install peer dependencies yourself.```

Is this an actual compatibility issue or is it sufficient to fix the supported version number in the `package.json`?

**Comment by mikaelbr** [comment]
You can test the master branch now (`npm i mikaelbr/marked-terminal`)

**Comment by mikaelbr** [comment]
Out now
