### ISSUE TITLE
How to display a vertical bar in a table

### ISSUE THREAD

**Issue by jeffeld** [mikaelbr/marked-terminal#55]
I'm rendering some structured data into a table. One of the fields has a verticle bar | in it, and naturally marked sees this as a directive to close the table cell.

I've tried escaping the symbol `&#124;` 
I've tried back ticks

But no luck. 

Is this possible?

Thanks!

**Comment by mikaelbr** [comment]
Hi. It looks like there's an open issue on marked about this, I'm afraid: https://github.com/markedjs/marked/issues/980

**Comment by jeffeld** [comment]
Thanks for the pointer!
