### ISSUE TITLE
allow image function override

### ISSUE THREAD

**Issue by arsdehnel** [mikaelbr/marked-terminal#58]
I'm just starting to work on implementing this package to do some previewing of a site that's almost entirely markdown before we publish it.  Initially it was working nicely but one of the problems we're trying to help resolve with this preview capability is that we've had a few times where the markdown doesn't reference an image properly or doesn't have any alt text.  I was hoping to be able to override the `image()` handler [here](https://github.com/mikaelbr/marked-terminal/blob/master/index.js#L216) by setting a new `image()` function in the options object.  Looks like that's not possible right now and if I'm reading the code right I should be able to just add some logic to check for `this.o.image()` existing and if that's set then use it, otherwise use the default one.  Or perhaps the `compose()` option is preferred as I see that in a few other handlers.

Maybe there is more to handling the `image()` that I'm not aware of?

**Comment by mikaelbr** [comment]
Hi, thanks for this issue! It's been added as an interface now. With the new version (v4, released soon) it should work as expected with overriding `image` in options.
