### ISSUE TITLE
Release version 4.1.1

### ISSUE THREAD

**Issue by thislooksfun** [mikaelbr/marked-terminal#66]
Now that #64 has been merged, the only thing remaining for this fix is to release a new version.

**Comment by felipecrs** [comment]
cc @mikaelbr

**Comment by mikaelbr** [comment]
I've been trying to solve #67 for for a couple of hours last few days but haven't traced the source of the extra whitespace as of yet.

**Comment by marcusrbrown** [comment]
Hi, thanks for looking into the whitespace bug. I have a project that incorporates `npm ls` in its tests that fails because it depends on `semantic-release` (which needs `marked@2`). Could you release 4.1.1 and release the bug fix in a later version?

**Comment by mikaelbr** [comment]
Tested more on old versions now and seems it is an existing issue. Releasing 4.1.1 now

**Comment by thislooksfun** [comment]
Thank you!
