### ISSUE TITLE
Question: change color of console.logs and integers?

### ISSUE THREAD

**Issue by yichenzhu1337** [mikaelbr/marked-terminal#69]
I'm wondering is there a way to change certain things like console.logs and integers to a different color? For example, I might want to change it to yellow or red.

<img width="812" alt="Screen Shot 2021-04-01 at 11 02 07 AM" src="https://user-images.githubusercontent.com/5568871/113314324-32ef4700-92da-11eb-86d8-838197f3aaa9.png">

**Comment by mikaelbr** [comment]
It should be possible to override the theme and create your own colors. Highlighting is done using cardinal and options to cardinal can be passed as second argument to the marked-terminal Renderer. See how you can create your own theme: https://github.com/thlorenz/cardinal/tree/master/themes
