### ISSUE TITLE
Introduce hybrid cjs/esm support?

### ISSUE THREAD

**Issue by AviVahl** [mikaelbr/marked-terminal#97]
heya @mikaelbr, thanks for your library.
`marked@4.0.10` supports both cjs and esm. would you consider accepting a PR that bundles `index.js` into an additional `index.cjs`, reviving support for cjs as well?

I'm asking because I've installed `firebase-tools`, which uses this library, and got the following:
`warning "firebase-tools > marked-terminal@3.3.0" has incorrect peer dependency "marked@^0.4.0 || ^0.5.0 || ^0.6.0 || ^0.7.0".`

`firebase-tools` is cjs. they upgraded to the latest `marked@4 `(due to a security issue), but couldn't upgrade `marked-terminal`, as it's esm only.

WDYT?

**Comment by mikaelbr** [comment]
Hi! Sure, I don't remember the details but I believe marked post 4 required ESM and that's the reason why I migrated. I see now that marked supports CJS as well, so it makes sense for this project to handle it in the same way. If you're willing to send a PR on this it would be much appreciated!

**Comment by AviVahl** [comment]
Awesome.
I believe marked re-added cjs support in v4.0.2: https://github.com/markedjs/marked/releases/tag/v4.0.2

There are two possible solutions:
1. downgrade to ansi-escapes@4 and use cjs for codebase.
2. bundle the esm sources to an additional cjs entry.

both solutions would work for both esm/cjs consumers. which do you prefer?
the former has the benefit of not requiring special building or anything of that sort.

**Comment by mikaelbr** [comment]
The ESM vs CJS divide is kind of difficult right now in a way. The virality of ESM causes other packages to require it, but also for some that's the direction the platform is heading, but not for everyone. But right now I think introducing a simple build step to bundle feels more future proof. What do you think?

**Comment by AviVahl** [comment]
TBH, in several packages I manage, I've either gone with pure-esm or pure-cjs to avoid cases where two different consumers get two different instances of the same code. This matters less for libraries such as `marked-terminal`, so one could go either way.

I'll create a PR doing the bundling and we'll see how it goes... :)

**Comment by mikaelbr** [comment]
Agreed. Not the biggest factor here. Using bundling for CJS in this case it could just be deleted at a potential future point where it is no longer needed.

**Comment by mikaelbr** [comment]
@AviVahl Released as 5.1.0 . Test out in firebase-tools now if it works better. Thanks again

**Comment by AviVahl** [comment]
I just checked. I forget to add "index.cjs" to the "files" field of package.json :( just checked 5.1.0 and published package doesn't include it. my bad.

**Comment by mikaelbr** [comment]
Check v5.1.1. v5.1.0 deprecated now

**Comment by AviVahl** [comment]
Thank you. I've tested it in `firebase-tools` and everything appears to work properly. Much appreciated.

**Comment by mikaelbr** [comment]
Very good! Thanks for the update
